### ISSUE TITLE
Needs update since 0.19.x for isNil of strings and seqs

### ISSUE THREAD

**Issue by genotrance** [ba0f3/xml.nim#1]

**Comment by ba0f3** [comment]
roger  that

**Comment by genotrance** [comment]
Thanks! I'm actively using xml in my [text editor](https://github.com/genotrance/feud) to create a table at compile time. I think the selector API doesn't work at compile time, though I'm not really using it.

**Comment by ba0f3** [comment]
awesome project! thank you for your interesting
